# Generated by Django 5.1.7 on 2025-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/campuses'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('lecture hall', 'Lecture Hall'), ('laboratory', 'Laboratory'), ('seminar room', 'Seminar Room'), ('female washroom', 'Female Washroom'), ('male washroom', 'Male Washroom'), ('cafeteria', 'Cafeteria')], max_length=50),
        ),
    ]
