# Generated by Django 5.1.7 on 2025-11-28 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='building',
            name='floors_num',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.CreateModel(
            name='FloorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/floor_maps/')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='uni.building')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uni.floormap'),
        ),
    ]
