# Generated by Django 5.1.7 on 2025-12-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_alter_room_options_remove_building_floors_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='map_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
