# Generated by Django 5.1.7 on 2025-12-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_room_map_x_room_map_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='uni.floormap'),
        ),
    ]
