# Generated by Django 5.1.7 on 2025-12-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_alter_room_floor_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingalias',
            old_name='alias',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='campusalias',
            old_name='alias',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='roomalias',
            old_name='alias',
            new_name='name',
        ),
    ]
