# Generated by Django 5.1.7 on 2025-12-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_rename_alias_buildingalias_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingalias',
            options={'verbose_name_plural': 'Building Aliases'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='campusalias',
            options={'verbose_name_plural': 'Campus Aliases'},
        ),
        migrations.AlterModelOptions(
            name='roomalias',
            options={'verbose_name_plural': 'Room Aliases'},
        ),
    ]
