# Generated by Django 5.1.7 on 2025-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_alter_buildingalias_options_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildings'),
        ),
    ]
