# Generated by Django 5.1.7 on 2025-12-02 15:12

import class_schedule.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.URLField(blank=True, help_text='Original university .ics feed link (optional)', null=True)),
                ('token', models.CharField(default=class_schedule.models.generate_token, max_length=128, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uid', models.CharField(blank=True, help_text='UID from the source VEVENT if present', max_length=512, null=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=512)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('raw_ics', models.TextField(blank=True, help_text='Optional raw VEVENT text for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['user', 'start'], name='class_sched_user_id_db7836_idx'), models.Index(fields=['user', 'source_uid'], name='class_sched_user_id_8faab7_idx')],
            },
        ),
    ]
